# ServerCommand 配置文件
hub-server: "hub"  # hub命令目标服务器名称

# 服务器别名配置
# 玩家可以使用这些别名来代替实际的服务器名称
# 例如：输入 /sc 生存 会传送到 srv-1 服务器
server-aliases:
  hub: "lobby-1"      # 大厅服务器
  lobby: "lobby-1"    # 大厅服务器
  "大厅": "lobby-1"   # 大厅服务器
  
  survival: "srv-1"   # 生存服务器
  "生存": "srv-1"     # 生存服务器
  
  creative: "crt-1"   # 创造服务器
  "创造": "crt-1"     # 创造服务器
  
  skyblock: "sky-1"   # 空岛服务器
  "空岛": "sky-1"     # 空岛服务器 